version: '3.3'
services:

  foodgram_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
    - ./.env

  foodgram_backend:
    image: rock4ts/foodgram-api:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx-foodgram/default.conf:/etc/nginx/conf.d/default.conf
      - ../foodgram-docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/django/
      - media_value:/var/html/media/
    depends_on:
      - foodgram_backend

volumes:
  static_value:
  media_value:
