# Generated by Django 2.2.28 on 2023-05-30 13:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_follow_constraint',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique follow constraint'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower=django.db.models.expressions.F('author')), name='self follow constraint'),
        ),
    ]
